spring:
  application:
    name: SpringBootStudyRoadmap
  data:
    mongodb:
      uri: mongodb+srv://springamit:Jy4DRjCfkGBUrfJ9@cluster0.zwwdlkd.mongodb.net/?appName=Cluster0
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.mongodb.driver: DEBUG